services:
  db:
    image: postgres:16-alpine
    container_name: eventpulse_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: EventPulseDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    container_name: eventpulse_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: